<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Fast_Mapper.Benchmarks</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fast-Mapper.Core\Fast-Mapper.Core.csproj" />
    <ProjectReference Include="..\..\src\Fast-Mapper.Sample\Fast-Mapper.Sample.csproj" />
  </ItemGroup>

</Project>
